version : '3.5'

services:
  kotlin-resful-api:
    container_name: kotlin-restful-api
    image: kotlin-restful-api:0.0.1
    ports:
      - 8080:8080
    environment:
      DATABASE_USERNAME: kotlin
      DATABASE_PASSWORD: kotlin
      DATABASE_URL: jdbc:postgresql://kotlin-restful-api-postgres:5432/restfull-api
  kotlin-resful-api-postgress:
    container_name: "kotlin-restful-api-postgres"
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: kotlin
      POSTGRES_USER: kotlin
      POSTGRES_DB: restfull-api